[[established_account]]
vp = "vp_user"
threshold = 1
public_keys = ["tpknam1qqwfpuvn8x7yqtquejhppef4vddv9ghusec2rkaxav38amamxaxpgj9cs79"]

[[established_account]]
vp = "vp_user"
threshold = 1
public_keys = ["tpknam1qq52dx5e290wyh7ngdt6wudtyd502lg6ln49yvg3vz97e8j2ruux5e3yewq"]

[[established_account]]
vp = "vp_user"
threshold = 1
public_keys = ["tpknam1qrnw8mxyqlj60mykgevnldcj5mg2fya7fs5a8xqdkd2gwtxhef0zy8a2wha"]

[[bond]]
source = "tnam1qxfj3sf6a0meahdu9t6znp05g8zx4dkjtgyn9gfu"
validator = "tnam1q9vhfdur7gadtwx4r223agpal0fvlqhywylf2mzx"
amount = "20000"

[bond.signatures]
tpknam1qrnw8mxyqlj60mykgevnldcj5mg2fya7fs5a8xqdkd2gwtxhef0zy8a2wha = "signam1qrutp8cqrnld9elq5lj7rxpyalljw867k2apl42sls7327uq90ya0hcjl84zguf5jqx0k3vmuw55h6a7wuutx422c2qt35fh3vvvtvq8qh0yg8"
