name: Lint

on:
  push:
    branches:
      - main
  # Run in PRs with conflicts (https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request)
  pull_request_target:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

env:
  GIT_LFS_SKIP_SMUDGE: 1
  FORCE_COLOR: 1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: earthly/actions-setup@v1
      with:
        version: v0.8.0
    - name: Checkout repo
      uses: actions/checkout@v4
      if: ${{ github.event_name != 'pull_request_target' }}
    - name: Checkout PR
      uses: actions/checkout@v4
      if: ${{ github.event_name == 'pull_request_target' }}
    - name: Select earthly satellite
      run: earthly sat select ${{ secrets.SATELLITE_ONE_ID }}
    - name: Run build
      run: earthly --ci +lints
