name: Audit

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

env:
  GIT_LFS_SKIP_SMUDGE: 1
  CARGO_INCREMENTAL: 0
  RUST_BACKTRACE: full

jobs:
  cron:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        branch: [main, draft]
        nightly_version: [nightly-2024-05-15]
        make:
          - name: cargo-audit
            tool: audit
          - name: cargo-machete
            command: machete

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: ${{ matrix.branch }}
      - name: Setup rust nightly
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ matrix.nightly_version }}
      - name: Install ${{ matrix.make.name }}
        uses: taiki-e/install-action@v2
        with:
          tool: ${{ matrix.make.tool }}
      - name: Install libudev
        run: sudo apt-get update && sudo apt-get -y install libudev-dev
      - name: Install Protoc
        uses: heliaxdev/setup-protoc@v2
        with:
          version: "25.0"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run ${{ matrix.make.name }}
        run: cargo ${{ matrix.make.command }}
